export const STORE = {
  name: "ครัวบ้านฮิม",
  tagline: "อาหารไทยโฮมเมด",
  owner: "อับดุลรอฮิม",
};

export const TABLES = [
  ["A1", "ว่าง", 4],
  ["A2", "กำลังใช้งาน", 2],
  ["A3", "ว่าง", 4],
  ["A4", "รอชำระเงิน", 6],
  ["B1", "ว่าง", 2],
  ["B2", "ว่าง", 4],
  ["B3", "กำลังใช้งาน", 4],
  ["B4", "ว่าง", 2],
  ["C1", "ว่าง", 8],
  ["C2", "ปิดใช้งาน", 6],
  ["C3", "ว่าง", 4],
  ["C4", "กำลังใช้งาน", 4],
].map(([name, status, seats]) => ({
  name,
  status,
  seats,
  zone: name[0],
  sort: name,
}));

export const MENU_ITEMS = [
  {
    name: "ข้าวกะเพราเนื้อไข่ดาว",
    category: "อาหารจานเดียว",
    price: 89,
    description: "กะเพราเนื้อหอมกระทะ เสิร์ฟพร้อมไข่ดาวกรอบ",
    imageUrl: "",
    emoji: "🍳",
    tone: "#fff0dd",
    available: true,
    bestseller: true,
  },
  {
    name: "ต้มยำกุ้งน้ำข้น",
    category: "ต้ม / แกง",
    price: 159,
    description: "กุ้งสด น้ำต้มยำเข้มข้น เปรี้ยวเผ็ดกำลังดี",
    imageUrl: "",
    emoji: "🍲",
    tone: "#ffe1d4",
    available: true,
    bestseller: true,
  },
  {
    name: "ผัดไทยกุ้งสด",
    category: "อาหารจานเดียว",
    price: 129,
    description: "เส้นเหนียวนุ่ม ซอสผัดไทยทำเอง กุ้งตัวใหญ่",
    imageUrl: "",
    emoji: "🍜",
    tone: "#fff2bd",
    available: true,
    bestseller: false,
  },
  {
    name: "ไก่ทอดซอสเกาหลี",
    category: "ทานเล่น",
    price: 119,
    description: "ไก่ทอดกรอบคลุกซอสเกาหลีหวานเผ็ด",
    imageUrl: "",
    emoji: "🍗",
    tone: "#ffd9c2",
    available: true,
    bestseller: false,
  },
  {
    name: "ชาไทยเย็น",
    category: "เครื่องดื่ม",
    price: 55,
    description: "ชาไทยเข้ม หวานมัน หอมกลิ่นชา",
    imageUrl: "",
    emoji: "🧋",
    tone: "#f7d8b8",
    available: true,
    bestseller: false,
  },
  {
    name: "ข้าวเหนียวมะม่วง",
    category: "ของหวาน",
    price: 79,
    description: "มะม่วงสุกหวาน ข้าวเหนียวมูนหอมกะทิ",
    imageUrl: "",
    emoji: "🥭",
    tone: "#fff0a9",
    available: true,
    bestseller: false,
  },
];

export const ORDERS = [
  {
    number: 1042,
    table: "A2",
    status: "กำลังเตรียม",
    paymentStatus: "ยังไม่ชำระ",
    source: "qr",
    items: [
      { name: "ข้าวกะเพราเนื้อไข่ดาว", price: 89, quantity: 2 },
    ],
  },
  {
    number: 1041,
    table: "B3",
    status: "รอรับออเดอร์",
    paymentStatus: "ยังไม่ชำระ",
    source: "qr",
    items: [
      { name: "ต้มยำกุ้งน้ำข้น", price: 159, quantity: 1 },
      { name: "ชาไทยเย็น", price: 55, quantity: 2 },
    ],
  },
  {
    number: 1040,
    table: "A4",
    status: "รอชำระเงิน",
    paymentStatus: "ยังไม่ชำระ",
    source: "staff",
    items: [
      { name: "ผัดไทยกุ้งสด", price: 129, quantity: 2 },
    ],
  },
];
